name: Bump App Version CI

on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: "20 */4 * * *"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    env:
      OWNER: FriesI23
      REPO: mhabit
      PATCH_NAME: changes.patch
    outputs:
      patch-name: ${{ env.PATCH_NAME }}
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: flathub/io.github.friesi23.mhabit
          ref: master
          token: ${{ secrets.AUTO_CI_TOKEN }}
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install packaging pyyaml toml
      - run: |
          cd ..
          curl -L https://github.com/TheAppgineer/flatpak-flutter/archive/refs/tags/0.7.3.tar.gz \
            -o flatpak-flutter.tar.gz
          tar -xzf flatpak-flutter.tar.gz
          mv flatpak-flutter-0.7.3 flatpak-flutter
      - name: Get Latest Release
        id: release-info
        env:
          GH_TOKEN: ${{ secrets.AUTO_CI_TOKEN }}
          REPO: ${{ env.OWNER }}/${{ env.REPO }}
        run: |
          TAG=$(
            gh release list \
              --exclude-pre-releases \
              --exclude-drafts \
              --repo $REPO \
              --limit 1 \
              --json tagName \
              --jq '.[0].tagName'
          )
          COMMIT=$(gh api repos/$REPO/git/ref/tags/$TAG -q .object.sha)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
      - name: Show Release Info
        run: |
          echo "Latest tag: ${{ steps.release-info.outputs.tag }}"
          echo "Commit SHA: ${{ steps.release-info.outputs.commit }}"
      - name: Update flatpak-flutter.yml
        env:
          FILE: flatpak-flutter.yml
          URL: https://github.com/FriesI23/mhabit.git
          NEW_TAG: ${{ steps.release-info.outputs.tag }}
          NEW_COMMIT: ${{ steps.release-info.outputs.commit }}
        run: >
          yq -i e
          '(.modules[].sources[] | select(.url == env(URL)) | .tag) = env(NEW_TAG)
          | (.modules[].sources[] | select(.url == env(URL)) | .commit) = env(NEW_COMMIT)'
          "$FILE"
      - name: Check for changes
        id: diff
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Build Flatpak Flutter
        if: steps.diff.outputs.changed == 'true'
        run: |
          mkdir -p assets/l10n
          touch assets/l10n/_untranslated.json
          python3 ../flatpak-flutter/flatpak-flutter.py flatpak-flutter.yml
          rm -fr assets
      - name: Create PR
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.AUTO_CI_TOKEN }}
          commit-message: "chore: bump version to ${{ steps.release-info.outputs.tag }}"
          branch: "release/${{ steps.release-info.outputs.tag }}"
          delete-branch: true
          title: "Released: ${{ steps.release-info.outputs.tag }}"
          body: |
            - Link: [${{ steps.release-info.outputs.tag }}][1]
            - Auto-generated by [create-pull-request][2]

            [1]: https://github.com/FriesI23/mhabit/releases/tag/${{ steps.release-info.outputs.tag }}
            [2]: https://github.com/peter-evans/create-pull-request
          assignees: FriesI23
          maintainer-can-modify: true
          push-to-fork: FriesI23/flathub-io.github.friesi23.mhabit
          draft: false
      - name: Clear
        if: always()
        run: |
          rm -fr assets
